name: ğŸš€ Deploy
on: workflow_dispatch
  # Commenting the below out for early dev
  # Will be running actions locally for time being.
  # push:
  #   branches:
  #     - main
  #     - dev
  #   paths-ignore:
  #     - content/**
  #     - .github/workflows/refresh-content.yml
  #     - README.md

  # pull_request:
  #   paths-ignore:
  #     - content/**
  #     - .github/workflows/refresh-content.yml
  #     - README.md

jobs:
  build:
    name: ğŸ‹ Build
    timeout-minutes: 15
    if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: ğŸ“ Checkout Repo
        uses: actions/checkout@v3

      - name: ğŸ“– Get App Name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: 'fly.toml'
          field: 'app'

      - name: ğŸ‹ Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.9.1
        
      - name: ğŸ’½ Cache Docker Layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-
      
      - name: ğŸ” Authenticate to Fly Registry
        uses: docker/login-action@v2
        with:
          registry: registry.fly.io
          username: x
          password: ${{ secrets.FLY_API_TOKEN }}
      
      - name: ğŸ‹ Docker Build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags:
            registry.fly.io/${{ steps.app_name.outputs.value }}:${{github.ref_name}}-${{ github.sha }}
          build-args: |
            COMMIT_CHA=${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,mode=max,dest=/tmp/.buildx-cache-new

      - name: â˜ï¸ Update Main Cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

  deploy:
    name: ğŸš€ Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    needs: [ build ]
    if: ${{ (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/dev') && github.event_name == 'push' }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: ğŸ“ Checkout Repo
        uses: actions/checkout@v3

      - name: ğŸ“– Get App Name
        uses: SebRollen/toml-action@v1.0.0
        id: app_name
        with:
          file: 'fly.toml'
          field: 'app'

      - name: ğŸš€ Deploy Staging
        if: ${{ github.ref == 'refs/heads/dev' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args:
            'deploy --app ${{ steps.app_name.outputs.value }}-staging --image registry.fly.io/${{ steps.app_name.outputs.value }}:${{ github.ref_name }}-${{ github.sha }}'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: ğŸš€ Deploy Production
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: superfly/flyctl-actions@1.3
        with:
          args:
            'deploy --image registry.fly.io/${{ steps.app_name.outputs.value
            }}:${{ github.ref_name }}-${{ github.sha }}'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}