name: Refresh Markdown Content
on:
  push:
    branches:
      - main
    paths:
      - content/**


jobs:
  refresh:
    name: Refresh Content
    runs-on: ubuntu-latest


    steps:

      - name: ğŸ“ Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: "2"

      - name: ğŸ“ Get Changed Files in Content Directory
        id: changed-files
        uses: tj-actions/changed-files@v35
        with:
          files: content/**

      - name: ğŸª Refresh Webhook
        if: steps.changed-files.outputs.any_changed == 'true'
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.REFRESH_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.REFRESH_WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.REFRESH_WEBHOOK_AUTH }}
          data: '{ "content": "${{ steps.changed-files.outputs.all_modified_files }}" }'