name: Refresh Markdown Content
on:
  push:
    branches:
      - main
    paths:
      - content/**


jobs:
  refresh:
    name: Refresh Content
    runs-on: ubuntu-latest


    steps:
      - name: ğŸ“ Get Changed Files
        uses: jitterbit/get-changed-files@v1
        id: files
      - run: |
          echo ${{ steps.files.outputs }} 


      - name: ğŸª Refresh Webhook
        uses: distributhor/workflow-webhook@v2
        env:
          webhook_url: ${{ secrets.REFRESH_WEBHOOK_URL }}
          webhook_secret: ${{ secrets.REFRESH_WEBHOOK_SECRET }}
          webhook_auth: ${{ secrets.REFRESH_WEBHOOK_AUTH }}
          data: ${{ steps.files.outputs }}